// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class Teste123Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
  //  driver.quit();
  }
  @Test
  public void teste123() {
    driver.get("https://batteriesplus-uat.repairq.io/");
    driver.manage().window().setSize(new Dimension(1129, 775));
    driver.findElement(By.linkText("Customers")).click();
    driver.findElement(By.id("listViewOptionsBtn")).click();
    driver.findElement(By.id("listsEdit")).click();
    driver.findElement(By.id("UserLoginForm_username")).sendKeys("l.costa@cinq.com");
    driver.findElement(By.id("UserLoginForm_password")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-new")).click();
    driver.findElement(By.id("UserLoginForm_password")).click();
    driver.findElement(By.id("UserLoginForm_password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("UserLoginForm_password")).sendKeys("123");
    driver.findElement(By.id("UserLoginForm_username")).click();
    driver.findElement(By.id("UserLoginForm_username")).sendKeys("l.costa@cinq.com.br");
    driver.findElement(By.id("UserLoginForm_password")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("UserLoginForm_username")).sendKeys("l.costa@cinq.com.br");
    driver.findElement(By.linkText("Tickets")).click();
    driver.findElement(By.linkText("5236")).click();
  }
}
